### ISSUE TITLE
Enhancement: new_imdbmapper path variable for tasks

### ISSUE THREAD

**Issue by tavoc** [DeBaschdi/EPGScripts#3]
The Path Variable could be an Argument of imdbtask_x.pl, therefore a user dont have to change 5 positions for path.

At the moment the path has to be configured in run.pl and all imdbtask.pl Files.

**Comment by DeBaschdi** [comment]
FIXED in
https://github.com/DeBaschdi/EPGScripts/commit/97d7a37ab275b5582e2c97c7b1f5f0e27a194b7d

**Comment by DeBaschdi** [comment]
Some more fixes was applied to this enhancement.
