### ISSUE TITLE
Fehler beim Aufruf vom genremapper

### ISSUE THREAD

**Issue by poFaber** [DeBaschdi/EPGScripts#5]
Ohne Parameter:
Odd number of elements in hash assignment at ./genremapper.pl line 100
Mit Parameter:
perl genremapper.pl  < guide.xml > new.xml
Odd number of elements in hash assignment at genremapper.pl line 100.

**Comment by visudo73** [comment]
Die oben genante Fehlermeldung kann ich bestätigen.

**Comment by visudo73** [comment]
Lesen hilft, das ist nur eine Warnug, das Script läuft einwandfrei
